// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPEFzXio5AqVcVwZtDPtViyz--3RUACFE',
    appId: '1:326459057588:web:6155a0dfaf26660c06fee1',
    messagingSenderId: '326459057588',
    projectId: 'flutter-remote-config-de-24990',
    authDomain: 'flutter-remote-config-de-24990.firebaseapp.com',
    storageBucket: 'flutter-remote-config-de-24990.appspot.com',
    measurementId: 'G-YNGG43070L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS7T_W6LXin-u--_RAd_h41jU74IR0kHE',
    appId: '1:326459057588:android:958e1b26bdd1be2c06fee1',
    messagingSenderId: '326459057588',
    projectId: 'flutter-remote-config-de-24990',
    storageBucket: 'flutter-remote-config-de-24990.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX0GAxlIQ0Y0sqjRNGGb2rrlIJs2HymE0',
    appId: '1:326459057588:ios:805de66fe4c3f62706fee1',
    messagingSenderId: '326459057588',
    projectId: 'flutter-remote-config-de-24990',
    storageBucket: 'flutter-remote-config-de-24990.appspot.com',
    iosClientId: '326459057588-sgsater2e17v1t2bf0h705sr4q0p4tlh.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseRemoteConfigDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX0GAxlIQ0Y0sqjRNGGb2rrlIJs2HymE0',
    appId: '1:326459057588:ios:4d1177e3aaf2926c06fee1',
    messagingSenderId: '326459057588',
    projectId: 'flutter-remote-config-de-24990',
    storageBucket: 'flutter-remote-config-de-24990.appspot.com',
    iosClientId: '326459057588-semqi8gudu2bp2hmdolpio13lqr89ks2.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseRemoteConfigDemo.RunnerTests',
  );
}
